[build-system]
requires = ["setuptools>=62.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-cdm"
version = "0.0.1"
requires-python = ">= 3.10"
dependencies = [
    "pydantic"
]

[tool.setuptools.packages.find]
where = ["src"]
